### ISSUE TITLE
Sharing direct links with others

### ISSUE THREAD

**Issue by akash-ramaswamy** [AngelineReetuA/github-analyser#1]
Implement a feature that allows users to land directly on a specific GitHub user's profile by providing a URL with the username appended. For example, accessing the URL `/user/:username` would take the user directly to that user's page without any additional steps. 

EDIT: This would help people to directly share their analysis link with others (especially in resume)

**Comment by AngelineReetuA** [comment]
Hi Akash.. yes that seems like a wonderful idea :) will work on it and keep you posted

**Comment by AngelineReetuA** [comment]
Hi @akash-ramaswamy , that issue is solved now and I have added a few more UI changes as well. Thanks for using the app !! :)
